// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://fireacademy.io/terms-and-conditions.txt",
        "contact": {
            "name": "yakuhito",
            "url": "https://twitter.com/yakuh1t0",
            "email": "y@kuhi.to"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/FireAcademy/beta/blob/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "The API key can be passed in the URL (between host and /beta), as a header (X-API-Key), or as a GET parameter (?api-key=)(also works for POST requests)",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "kraken.fireacademy.io",
	BasePath:         "/beta",
	Schemes:          []string{},
	Title:            "Beta API",
	Description:      "The Beta FireAcademy.io API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
